# Generated by Django 3.2.12 on 2022-05-23 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='is_seen',
            field=models.BooleanField(null=True),
        ),
    ]
